Verify shasums and pgp signatures
[#148919557](https://www.pivotaltracker.com/story/show/148919557)

Signed-off-by: Chris Dutra <cdutra@pivotal.io>

diff --git a/ci/docker/bosh.vsphere-cpi-release/Dockerfile b/ci/docker/bosh.vsphere-cpi-release/Dockerfile
--- a/ci/docker/bosh.vsphere-cpi-release/Dockerfile
+++ b/ci/docker/bosh.vsphere-cpi-release/Dockerfile
@@ -5,58 +5,52 @@ RUN dpkg-reconfigure locales
 ENV LANG en_US.UTF-8
 ENV LC_ALL en_US.UTF-8
 
-RUN apt-get update; apt-get -y upgrade; apt-get clean
+RUN apt-get update && \
+    apt-get install -y --no-install-recommends \
+    ca-certificates \
+    git curl wget tar make \
+    sqlite3 libsqlite3-dev \
+    mysql-client libmysqlclient-dev \
+    postgresql-9.3 postgresql-client-9.3 libpq-dev \
+    jq realpath && \
+    apt-get clean
 
-RUN apt-get install -y git curl wget tar make; apt-get clean
+RUN apt-get install -y --no-install-recommends python
 
-RUN apt-get install -y sqlite3 libsqlite3-dev; apt-get clean
+ENV RUBY_INSTALL_VERSION=0.6.1 CHRUBY_VERSION=0.3.9 RUBY_VERSION=2.2.6
 
-RUN apt-get install -y mysql-client libmysqlclient-dev; apt-get clean
+# Import Postmodern PGP key
+RUN wget -nv https://raw.github.com/postmodern/postmodern.github.io/master/postmodern.asc && \
+   gpg --import postmodern.asc && \
+   gpg --fingerprint 0xB9515E77 | grep 'Key fingerprint = 04B2 F3EA 6541 40BC C7DA  1B57 54C3 D9E9 B951 5E77' && \
+   if [ "$?" != "0" ]; then echo "Invalid PGP key!"; exit 1; fi
 
-RUN apt-get install -y postgresql-9.3 postgresql-client-9.3 libpq-dev; apt-get clean
-
-RUN apt-get install -y jq; apt-get clean
-
-RUN apt-get install -y realpath; apt-get clean
-
-RUN mkdir /tmp/python && \
-    cd /tmp && \
-    curl https://www.python.org/ftp/python/2.7.13/Python-2.7.13.tgz | tar -xz && \
-    cd /tmp/Python-2.7.13 && \
-    ./configure && \
-    make && make install && \
-    rm -rf /tmp/python
-
-# chruby
-RUN mkdir /tmp/chruby && \
-    cd /tmp && \
-    curl https://codeload.github.com/postmodern/chruby/tar.gz/v0.3.9 | tar -xz && \
-    cd /tmp/chruby-0.3.9 && \
-    sudo ./scripts/setup.sh && \
-    rm -rf /tmp/chruby
-
-# ruby-install
-RUN mkdir /tmp/ruby-install && \
-    cd /tmp && \
-    curl https://codeload.github.com/postmodern/ruby-install/tar.gz/v0.5.0 | tar -xz && \
-    cd /tmp/ruby-install-0.5.0 && \
-    sudo make install && \
-    rm -rf /tmp/ruby-install
-
-# ruby
-RUN ruby-install ruby 2.2.6
-
-# Install Bundler, Bosh CLI, and CPI Dependencies
-RUN /bin/bash -l -c "source /etc/profile.d/chruby.sh ;  \
-                     chruby 2.2.6 ;                     \
-                     gem update --system ; \
-                     gem install bundler bosh_cli --no-ri --no-rdoc ; \
-                     cd /tmp ; \
-                     git clone https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release.git ; \
-                     cd bosh-vsphere-cpi-release/src/vsphere_cpi ; \
-                     bundle install"
-
+# Install chruby
 RUN cd /tmp && \
-    curl -o certify-artifacts -L https://s3.amazonaws.com/bosh-certification-generator-releases/certify-artifacts-linux-amd64 && \
-    chmod +x certify-artifacts && \
-    mv certify-artifacts /bin/certify-artifacts
+   wget -nv -O chruby-$CHRUBY_VERSION.tar.gz https://github.com/postmodern/chruby/archive/v$CHRUBY_VERSION.tar.gz && \
+   wget -nv https://raw.github.com/postmodern/chruby/master/pkg/chruby-$CHRUBY_VERSION.tar.gz.asc && \
+   gpg --verify chruby-$CHRUBY_VERSION.tar.gz.asc chruby-$CHRUBY_VERSION.tar.gz && \
+   tar -xzvf chruby-$CHRUBY_VERSION.tar.gz && \
+   cd chruby-$CHRUBY_VERSION/ && \
+   sudo ./scripts/setup.sh && \
+   rm -rf /tmp/chruby-$CHRUBY_VERSION && rm /tmp/*
+
+# Install ruby-install
+RUN cd /tmp && \
+   wget -nv -O ruby-install-$RUBY_INSTALL_VERSION.tar.gz https://github.com/postmodern/ruby-install/archive/v$RUBY_INSTALL_VERSION.tar.gz && \
+   wget -nv https://raw.github.com/postmodern/ruby-install/master/pkg/ruby-install-$RUBY_INSTALL_VERSION.tar.gz.asc && \
+   gpg --verify ruby-install-$RUBY_INSTALL_VERSION.tar.gz.asc ruby-install-$RUBY_INSTALL_VERSION.tar.gz && \
+   tar -xzvf ruby-install-$RUBY_INSTALL_VERSION.tar.gz && \
+   cd ruby-install-$RUBY_INSTALL_VERSION/ && \
+   sudo make install && \
+   rm -rf /tmp/ruby-install-$RUBY_INSTALL_VERSION && rm /tmp/*
+
+# Install Ruby
+RUN ruby-install ruby $RUBY_VERSION -- --disable-install-rdoc
+
+# Install Bundler
+RUN /bin/bash -l -c "                            \
+  source /etc/profile.d/chruby.sh ;              \
+  chruby $RUBY_VERSION ;                         \
+  gem install bundler --no-ri --no-rdoc          \
+"
