Clean up unit and integration test scripts
Signed-off-by: Kaiting Chen <kaitingc@vmware.com>

diff --git a/src/vsphere_cpi/bin/check-ruby-version b/src/vsphere_cpi/bin/check-ruby-version
--- a/src/vsphere_cpi/bin/check-ruby-version
+++ b/src/vsphere_cpi/bin/check-ruby-version
@@ -1,22 +1,18 @@
-#!/usr/bin/env bash
+#! /bin/bash
 
-[[ ! -f /usr/local/share/chruby/chruby.sh ]] && brew install chruby
+[ -f /usr/local/share/chruby/chruby.sh ] || brew install chruby
 source /usr/local/share/chruby/chruby.sh
 
-chruby $PROJECT_RUBY_VERSION
-if [[ "$?" -eq "1" ]]; then
-  echo "Ruby version $PROJECT_RUBY_VERSION not found. Installing..."
+if ! chruby $PROJECT_RUBY_VERSION; then
+  echo "Ruby $PROJECT_RUBY_VERSION not found. Installing ..." 1>&2
 
-  which ruby-install > /dev/null 2>&1
-  [[ "$?" -eq "1" ]] && brew install ruby-install
+  command -v ruby-install > /dev/null 2>&1 || brew install ruby-install
 
-  echo "Installing Ruby version $PROJECT_RUBY_VERSION ..."
   ruby-install ruby $PROJECT_RUBY_VERSION
+  source /usr/local/share/chruby/chruby.sh
   chruby $PROJECT_RUBY_VERSION
 
-  echo "Ruby version $PROJECT_RUBY_VERSION successfully installed."
+  echo "Ruby $PROJECT_RUBY_VERSION successfully installed" 1>&2
 fi
-echo "Using ruby version $PROJECT_RUBY_VERSION"
 
-echo "Installing bundler..."
-gem install bundler
+command -v bundle > /dev/null 2>&1 || gem install bundler
