Revert bumping to Ruby 2
CPI does not compile on mac os.
Reverts:
- ef72eea63a89da35676de99c8b8eec885504b2ca
- acf64fb10c3f0718ed2be4400d17da62287de5a8
- aee120babce340c5082f72dbee7ce27b944d57c1
- 8cddde7011d7b9b8901c1198d8856a1cc00419a4
- f23d52b5c86dfc84a674854fc5386ec17e6d8147
- 535c76b267f52315ad3bbd81de059137f970d222

diff --git a/packages/vsphere_cpi_ruby/packaging b/packages/vsphere_cpi_ruby/packaging
--- a/packages/vsphere_cpi_ruby/packaging
+++ b/packages/vsphere_cpi_ruby/packaging
@@ -8,28 +8,34 @@ tar xzf vsphere_cpi_ruby/yaml-0.1.5.tar.gz
   make
   make install
 )
+if [[ $? != 0 ]] ; then
+  echo "Cannot install yaml"
+  exit 1
+fi
 
-tar xzf vsphere_cpi_ruby/ruby-2.1.4.tar.gz
+tar xzf vsphere_cpi_ruby/ruby-1.9.3-p545.tar.gz
 (
   set -e
-  cd ruby-2.1.4
-  LDFLAGS="-Wl,-rpath -Wl,${BOSH_INSTALL_TARGET}" CFLAGS='-fPIC' ./configure --prefix=${BOSH_INSTALL_TARGET} --disable-install-doc --with-opt-dir=${BOSH_INSTALL_TARGET} --without-gmp
+  cd ruby-1.9.3-p545
+  LDFLAGS="-Wl,-rpath -Wl,${BOSH_INSTALL_TARGET}" CFLAGS='-fPIC' ./configure --prefix=${BOSH_INSTALL_TARGET} --disable-install-doc --with-opt-dir=${BOSH_INSTALL_TARGET}
   make
   make install
 )
+if [[ $? != 0 ]] ; then
+  echo "Cannot install ruby"
+  exit 1
+fi
 
-tar zxvf vsphere_cpi_ruby/rubygems-2.3.0.tgz
-
+tar zxvf vsphere_cpi_ruby/rubygems-2.1.11.tgz
 (
   set -e
-  cd rubygems-2.3.0
+  cd rubygems-2.1.11
 
-  ${BOSH_INSTALL_TARGET}/bin/ruby setup.rb --no-ri --no-rdoc
-
-  if [[ $? != 0 ]] ; then
-    echo "Cannot install rubygems"
-    exit 1
-  fi
+  ${BOSH_INSTALL_TARGET}/bin/ruby setup.rb
 )
+if [[ $? != 0 ]] ; then
+  echo "Cannot install rubygems"
+  exit 1
+fi
 
-${BOSH_INSTALL_TARGET}/bin/gem install vsphere_cpi_ruby/bundler-1.6.3.gem --local --no-ri --no-rdoc
+${BOSH_INSTALL_TARGET}/bin/gem install vsphere_cpi_ruby/bundler-1.8.2.gem --local --no-ri --no-rdoc
