Updates vsphere cpi release to use bundler and remove db settings
[#80175188]
Signed-off-by: Corey Innis <cinnis@pivotal.io>

diff --git a/packages/ruby_vsphere_cpi/packaging b/packages/ruby_vsphere_cpi/packaging
--- a/packages/ruby_vsphere_cpi/packaging
+++ b/packages/ruby_vsphere_cpi/packaging
@@ -5,29 +5,37 @@ tar xzf ruby_vsphere_cpi/yaml-0.1.5.tar.gz
   set -e
   cd yaml-0.1.5
   CFLAGS='-fPIC' ./configure --prefix=${BOSH_INSTALL_TARGET} --disable-shared
-  make
-  make install
+  make -j
+  make -j install
 )
+if [[ $? != 0 ]] ; then
+  echo "Cannot install yaml"
+  exit 1
+fi
 
 tar xzf ruby_vsphere_cpi/ruby-1.9.3-p545.tar.gz
 (
   set -e
   cd ruby-1.9.3-p545
   LDFLAGS="-Wl,-rpath -Wl,${BOSH_INSTALL_TARGET}" CFLAGS='-fPIC' ./configure --prefix=${BOSH_INSTALL_TARGET} --disable-install-doc --with-opt-dir=${BOSH_INSTALL_TARGET}
-  make
-  make install
+  make -j
+  make -j install
 )
+if [[ $? != 0 ]] ; then
+  echo "Cannot install ruby"
+  exit 1
+fi
 
 tar zxvf ruby_vsphere_cpi/rubygems-2.1.11.tgz
-
 (
   set -e
   cd rubygems-2.1.11
 
   ${BOSH_INSTALL_TARGET}/bin/ruby setup.rb
-
-  if [[ $? != 0 ]] ; then
-    echo "Cannot install rubygems"
-    exit 1
-  fi
 )
+if [[ $? != 0 ]] ; then
+  echo "Cannot install rubygems"
+  exit 1
+fi
+
+${BOSH_INSTALL_TARGET}/bin/gem install ruby_vsphere_cpi/bundler-1.8.2.gem --local --no-ri --no-rdoc
